/**
 * Created by chj on 2018/4/17.
 */
// 保存页面key
export const ACTION_SAVE_ROUTEID = 'ACTION_SAVE_ROUTEID';

// 首页反向传值
export const ACTION_SEND_VALUE_FROM_NEXT = 'ACTION_SEND_VALUE_FROM_NEXT';

// 首页是否显示 hub
export const ACTION_CHANGE_HUB_STATE = 'ACTION_CHANGE_HUB_STATE';

// 保存首页接口信息
export const ACTION_SAVE_USER_INFO = 'ACTION_SAVE_USER_INFO';


// redux-promise
export const ACTION_DISPATCH_PROMISE = 'ACTION_DISPATCH_PROMISE';

// redux-promise-middleware
export const ACTION_DISPATCH_PROMISE_MIDDLEWARE = 'ACTION_DISPATCH_PROMISE_MIDDLEWARE',
             ACTION_DISPATCH_PROMISE_MIDDLEWARE_PENDING = 'ACTION_DISPATCH_PROMISE_MIDDLEWARE_PENDING',
             ACTION_DISPATCH_PROMISE_MIDDLEWARE_FULFILLED = 'ACTION_DISPATCH_PROMISE_MIDDLEWARE_FULFILLED',
             ACTION_DISPATCH_PROMISE_MIDDLEWARE_REJECTED = 'ACTION_DISPATCH_PROMISE_MIDDLEWARE_REJECTED';

// 自定义网络请求中间件，发送action进行网络请求
export const ACTION_MIDDLEWARE_HTTP = 'ACTION_MIDDLEWARE_HTTP';